#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/chef

PRODUCT_COPY_FILES += \
    vendor/motorola/chef/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/chef/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/chef/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/chef/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/chef/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/chef/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/chef/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/chef/proprietary/vendor/etc/camera/bokeh_preview.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bokeh_preview.cfg \
    vendor/motorola/chef/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/motorola/chef/proprietary/vendor/etc/camera/ov12a10_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov12a10_qtech_chromatix.xml \
    vendor/motorola/chef/proprietary/vendor/etc/camera/ov16b10_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16b10_qtech_chromatix.xml \
    vendor/motorola/chef/proprietary/vendor/etc/camera/ov5675_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5675_qtech_chromatix.xml \
    vendor/motorola/chef/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets.rc \
    vendor/motorola/chef/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/motorola/chef/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/motorola/chef/proprietary/vendor/etc/init/init.ets.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.ets.rc \
    vendor/motorola/chef/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_csot_nt_fhd_618.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_csot_nt_fhd_618.xml \
    vendor/motorola/chef/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_nt_fhd_618.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_nt_fhd_618.xml \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/motorola/chef/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw

PRODUCT_PACKAGES += \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    libQSEEComAPI \
    libcdsprpc \
    libdualcameraddm \
    libets_fp_et5 \
    libets_teeclient \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libseemore \
    libsensor1 \
    libsensor_reg \
    libvideobokeh \
    sensor_calibrate \
    sensors.rp \
    sensors.ssc \
    vendor.egistec.hardware.fingerprint@2.0 \
    camera.sdm660 \
    libSonyDefocus \
    libDepthBokehEffect \
    libS5k2l7Pdaf \
    libS5k2l7PdafCamif \
    libactuator_dw9714 \
    libactuator_fp5510e2 \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libchromatix_ov12a10_qtech_4k_preview_3a \
    libchromatix_ov12a10_qtech_4k_video_3a \
    libchromatix_ov12a10_qtech_common \
    libchromatix_ov12a10_qtech_cpp_hfr_120 \
    libchromatix_ov12a10_qtech_cpp_hfr_60 \
    libchromatix_ov12a10_qtech_cpp_hfr_90 \
    libchromatix_ov12a10_qtech_cpp_liveshot \
    libchromatix_ov12a10_qtech_cpp_preview \
    libchromatix_ov12a10_qtech_cpp_snapshot \
    libchromatix_ov12a10_qtech_cpp_snapshot_night_scene \
    libchromatix_ov12a10_qtech_cpp_video \
    libchromatix_ov12a10_qtech_cpp_video_4k \
    libchromatix_ov12a10_qtech_default_preview_3a \
    libchromatix_ov12a10_qtech_default_video \
    libchromatix_ov12a10_qtech_default_video_3a \
    libchromatix_ov12a10_qtech_default_video_4k \
    libchromatix_ov12a10_qtech_hfr_120 \
    libchromatix_ov12a10_qtech_hfr_120_3a \
    libchromatix_ov12a10_qtech_hfr_60 \
    libchromatix_ov12a10_qtech_hfr_60_3a \
    libchromatix_ov12a10_qtech_hfr_90 \
    libchromatix_ov12a10_qtech_hfr_90_3a \
    libchromatix_ov12a10_qtech_postproc \
    libchromatix_ov12a10_qtech_preview \
    libchromatix_ov12a10_qtech_snapshot \
    libchromatix_ov12a10_qtech_snapshot_night_scene \
    libchromatix_ov12a10_qtech_zsl_preview_3a \
    libchromatix_ov12a10_qtech_zsl_video_3a \
    libchromatix_ov16b10_qtech_common \
    libchromatix_ov16b10_qtech_cpp_hfr_120 \
    libchromatix_ov16b10_qtech_cpp_hfr_60 \
    libchromatix_ov16b10_qtech_cpp_hfr_90 \
    libchromatix_ov16b10_qtech_cpp_liveshot \
    libchromatix_ov16b10_qtech_cpp_preview \
    libchromatix_ov16b10_qtech_cpp_snapshot \
    libchromatix_ov16b10_qtech_cpp_snapshot_night_scene \
    libchromatix_ov16b10_qtech_cpp_video \
    libchromatix_ov16b10_qtech_default_preview_3a \
    libchromatix_ov16b10_qtech_default_video \
    libchromatix_ov16b10_qtech_default_video_3a \
    libchromatix_ov16b10_qtech_hfr_120 \
    libchromatix_ov16b10_qtech_hfr_120_3a \
    libchromatix_ov16b10_qtech_hfr_60 \
    libchromatix_ov16b10_qtech_hfr_60_3a \
    libchromatix_ov16b10_qtech_hfr_90 \
    libchromatix_ov16b10_qtech_hfr_90_3a \
    libchromatix_ov16b10_qtech_liveshot \
    libchromatix_ov16b10_qtech_postproc \
    libchromatix_ov16b10_qtech_preview \
    libchromatix_ov16b10_qtech_snapshot \
    libchromatix_ov16b10_qtech_snapshot_night_scene \
    libchromatix_ov16b10_qtech_zsl_preview_3a \
    libchromatix_ov16b10_qtech_zsl_video_3a \
    libchromatix_ov5675_qtech_a3_default_preview \
    libchromatix_ov5675_qtech_a3_default_video \
    libchromatix_ov5675_qtech_a3_hfr_120 \
    libchromatix_ov5675_qtech_a3_hfr_60 \
    libchromatix_ov5675_qtech_a3_hfr_90 \
    libchromatix_ov5675_qtech_common \
    libchromatix_ov5675_qtech_cpp_ds_chromatix \
    libchromatix_ov5675_qtech_cpp_hfr_120 \
    libchromatix_ov5675_qtech_cpp_hfr_60 \
    libchromatix_ov5675_qtech_cpp_hfr_90 \
    libchromatix_ov5675_qtech_cpp_liveshot \
    libchromatix_ov5675_qtech_cpp_preview \
    libchromatix_ov5675_qtech_cpp_snapshot \
    libchromatix_ov5675_qtech_cpp_us_chromatix \
    libchromatix_ov5675_qtech_cpp_video \
    libchromatix_ov5675_qtech_cpp_video_full \
    libchromatix_ov5675_qtech_default_video \
    libchromatix_ov5675_qtech_hfr_120 \
    libchromatix_ov5675_qtech_hfr_60 \
    libchromatix_ov5675_qtech_hfr_90 \
    libchromatix_ov5675_qtech_liveshot \
    libchromatix_ov5675_qtech_postproc \
    libchromatix_ov5675_qtech_preview \
    libchromatix_ov5675_qtech_snapshot \
    libchromatix_ov5675_qtech_video_full \
    libchromatix_ov5675_qtech_zsl_preview \
    libchromatix_ov5675_qtech_zsl_video \
    libcppf \
    libdepthmapwrapper \
    libfastcvadsp_stub \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_bokeh \
    libmmcamera_depth_map \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_ov12a10_qtech \
    libmmcamera_ov12a10_qtech_eeprom \
    libmmcamera_ov12a10_sunny \
    libmmcamera_ov12a10_sunny_eeprom \
    libmmcamera_ov16b10_qtech \
    libmmcamera_ov16b10_qtech_eeprom \
    libmmcamera_ov5675_qtech \
    libmmcamera_ov5675_qtech_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveFaceRecognition \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    libGPreqcancel \
    libGPreqcancel_svc \
    libSecureUILib \
    libStDrvInt \
    libdrmfs \
    libdrmtime \
    libhdcpsrm \
    liboemcrypto \
    libqisl \
    librpmb \
    libsecureui_svcsock \
    libssd \
    vendor.qti.hardware.tui_comm@1.0 \
    charge_only_mode \
    android.hardware.biometrics.fingerprint@2.1-service-ets \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    qseecomd \
    sensors.qti
